# Fake news Detection using Machine Learning

We will be doing analysis here

## Step 0 : Importing Important Dependencies

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string
from sklearn.model_selection  import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

## Step 1 : Data collection 

we will install / get two types of data 
1. Fake data
2. True data

In [3]:
true_df = pd.read_csv(r"D:\Robotics\Machine Learning Projects\Fake News Detection\data\True.csv")
false_df = pd.read_csv(r"D:\Robotics\Machine Learning Projects\Fake News Detection\data\Fake.csv")

In [4]:
true_df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [5]:
false_df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

## Step 3 : EDA

In [6]:
# Lets check the shape of the data
print(f'Shape of true data is {true_df.shape}')
print(f'Shape of false data is {false_df.shape}')

Shape of true data is (21417, 4)
Shape of false data is (23481, 4)

In [8]:
print((21417-23481))

-2064

#### Adding classes to the dataset

In [9]:
false_df["class"]=0
true_df["class"] = 1

In [10]:
false_df.head()

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [19]:
false_df.shape , true_df.shape

((23481, 5), (21417, 5))

In [20]:
fake_manual_testing = false_df.tail(10)
for i in range(23480 , 23470,-1):
    false_df.drop([i] , axis=0 , inplace=True)

true_data_manual_testing = true_df.tail(10)
for i in range(21416,21406,-1):
    true_df.drop([i],axis=0 , inplace=True)

In [21]:
false_df.shape, true_df.shape

((23471, 5), (21407, 5))